# Generated by Django 4.2 on 2023-04-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=False)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='targets.connections')),
            ],
        ),
        migrations.AddField(
            model_name='connections',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.items'),
        ),
    ]
