# Generated by Django 4.2 on 2023-04-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='connection',
        ),
        migrations.AddField(
            model_name='items',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='targets.items'),
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
    ]
